root = "."
tmp_dir = ".cache"

[build]
cmd = "go build -o ./.cache/polybase-web ./cmd/polybase-web"
bin = "./.cache/polybase-web -c polybase.cfg"
include_ext = ["go", "templ"]
exclude_dir = [".cache"]
delay = 100
stop_on_error = true

[log]
time = false
main_only = true

[screen]
clear_on_rebuild = false
