root = "."
tmp_dir = ".cache"

[build]
cmd = "tailwindcss -i static/css/tailwind.css -o static/css/styles.css --minify && templ generate && go build -o ./.cache/polybase-web ./cmd/polybase-web"
bin = "./.cache/polybase-web -c polybase.cfg"
include_ext = ["go", "templ"]
exclude_dir = [".cache"]
exclude_regex = ["_templ\\.go$"]
delay = 100
stop_on_error = true
kill_delay = 0
send_interrupt = true
rerun = false
rerun_delay = 500

[log]
time = false
main_only = true

[screen]
clear_on_rebuild = false

[misc]
clean_on_exit = true
