root = "."
tmp_dir = "target/cache"

[build]
# cmd = "tailwindcss -i static/css/main.css -o static/css/styles.css -m && templ generate && go build -o target/cache/polybased ./polybased"
cmd = "templ generate && go build -o target/cache/polybased ./polybased"
bin = "target/cache/polybased -c polybase.cfg"
include_ext = ["go", "templ"]
exclude_dir = ["target"]
exclude_regex = ["_templ\\.go$"]
delay = 100
stop_on_error = true
send_interrupt = true

[log]
time = false
main_only = true

[screen]
clear_on_rebuild = false

[misc]
clean_on_exit = true
