image: openbsd/latest
packages:
  - go
  - node
  - scdoc
sources:
  - https://git.sr.ht/~alias/polybase-go
tasks:
  - setup: |
      cd polybase-go
      go install github.com/a-h/templ/cmd/templ@v0.2.793

  - test: |
      cd polybase-go
      npx -y tailwindcss -i static/css/main.css -o static/css/styles.css -m
      ~/go/bin/templ generate
      go test ./...

  - build: |
      cd polybase-go
      mkdir -p target

      npx -y tailwindcss -i static/css/main.css -o static/css/styles.css -m

      ~/go/bin/templ generate

      scdoc < polybase.1.scd | sed "s/1980-01-01/$(date '+%B %Y')/" > target/polybase.1
      scdoc < polybased.1.scd | sed "s/1980-01-01/$(date '+%B %Y')/" > target/polybased.1

      go build -o target/polybased ./polybased
      go build -o target/polybase ./polybase

  - package: |
      cd polybase-go

      mkdir -p dist
      cp install.sh dist/

      mkdir -p dist/usr/local/bin
      cp target/polybased dist/usr/local/bin/
      cp target/polybase dist/usr/local/bin/

      mkdir -p dist/usr/local/man/man1
      cp target/polybase.1 dist/usr/local/man/man1/
      cp target/polybased.1 dist/usr/local/man/man1/

      mkdir -p dist/etc/polybase
      touch dist/etc/polybase/polybase.cfg

      mkdir -p dist/etc/rc.d
      cp polybased.rc dist/etc/rc.d/polybased

artifacts:
  - polybase-go/dist
