image: openbsd/latest
packages:
  - go
  - node
  - scdoc
sources:
  - https://git.sr.ht/~alias/polybase-go
tasks:
  - setup: |
      cd polybase-go
      go install github.com/a-h/templ/cmd/templ@latest

  - test: |
      cd polybase-go
      go test ./...

  - build: |
      cd polybase-go
      mkdir -p target

      npx tailwindcss -i static/css/tailwind.css -o static/css/styles.css --minify

      templ generate

      scdoc < polybase.1.scd | sed "s/1980-01-01/$(date '+%B %Y')/" > target/polybase.1
      scdoc < polybased.1.scd | sed "s/1980-01-01/$(date '+%B %Y')/" > target/polybased.1

      go build -o target/polybased ./polybased
      go build -o target/polybase ./polybase

  - package: |
      cd polybase-go

      mkdir -p dist/{bin,usr/local/man/man1,etc/polybase}

      cp install.sh dist/

      cp target/polybased dist/usr/local/bin/
      cp target/polybase dist/usr/local/bin/

      cp target/polybase.1 dist/usr/local/man/man1/
      cp target/polybased.1 dist/usr/local/man/man1/

      touch dist/etc/polybase/polybase.cfg

      cp polybased.rc dist/etc/rc.d/polybased

artifacts:
  - polybase-go/dist
