// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col min-h-screen\"><header class=\"mb-4 drop-shadow-lg\"><div class=\"px-4 py-2 drop-shadow-none\"><div class=\"flex items-center\"><a href=\"/\" class=\"text-accent-500 flex items-center gap-x-2\"><img class=\"size-12\" src=\"/static/svg/logo.svg\"><h1 class=\"text-3xl font-bold\">Polybase</h1></a></div></div><div class=\"bg-accent-500 text-accent-100 flex items-center justify-between drop-shadow-none\"><p class=\"px-4 py-2 truncate\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(GetRandomMessage())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/login.templ`, Line: 16, Col: 55}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div></header><div class=\"flex-grow flex flex-col items-center px-4\"><div class=\"w-full max-w-md my-auto\"><form hx-post=\"/auth\" class=\"bg-white rounded-lg px-6 py-8 drop-shadow-lg\"><h2 class=\"text-2xl font-bold mb-6\">Bienvenue sur Polybase !</h2><div class=\"space-y-4\"><div><label class=\"block text-gray-700 mb-2\" for=\"username\">Nom d'utilisateur</label> <input type=\"text\" id=\"username\" name=\"username\" required class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-accent-500\"></div><div><label class=\"block text-gray-700 mb-2\" for=\"password\">Mot de passe</label> <input type=\"password\" id=\"password\" name=\"password\" required class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-accent-500\"></div><div id=\"error-response\" class=\"text-sm text-red-500 text-center min-h-6\"></div><button type=\"submit\" class=\"w-full bg-accent-500 text-accent-100 py-2 rounded-lg hover:bg-accent-700 active:bg-accent-800 transition-colors\">Se connecter</button></div></form><div class=\"mt-6 text-sm text-center text-gray-600\"><p>Pas encore de compte ?</p><p class=\"mt-1\">Inscris-toi aux créneaux polys de l'ALIAS !</p></div></div></div><div class=\"border-t mt-auto\"><div class=\"px-12 py-4 flex items-center justify-between\"><span></span> <span>Fait par et pour l'ALIAS avec ❤️ </span></div></div></div><script>\n    document.addEventListener('htmx:beforeSwap', function(evt) {\n      if (evt.detail.xhr.status >= 400) {\n        evt.detail.shouldSwap = true;\n        evt.detail.isError = false;\n        evt.detail.target = document.getElementById('error-response');\n        }\n      });\n    </script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Base(true).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
