name: Build OpenBSD Package
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix build
      - uses: actions/upload-artifact@v3
        with:
          name: polybase-openbsd-dist
          path: result/
