name: Build Polybase
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: deploy-polybase
  cancel-in-progress: false

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Check diff between gofmt and code
        run: diff <(gofmt -d .) <(echo -n)
  build:
    name: Build polybase package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Install Bun 
        uses: oven-sh/setup-bun@v2

      - name: Install just and scdoc
        run: sudo apt install -y just scdoc

      - name: Install deps
        run: bun i

      - name: Build package
        run: just build
