name: Build Polybase
on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: deploy-polybase
  cancel-in-progress: false

jobs:
  build:
    name: Build polybase package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build package
        run: nix build
